name: Customer Data Store CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Build and Test
        run: mvn clean test
